import datetime
from collections.abc import Sequence
from typing import Any, Callable

from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import (
    dsa,
    ec,
    ed448,
    ed25519,
    rsa,
)

from OpenSSL._util import StrOrBytesPath as StrOrBytesPath

_PrivateKey = (
    dsa.DSAPrivateKey
    | ec.EllipticCurvePrivateKey
    | ed25519.Ed25519PrivateKey
    | ed448.Ed448PrivateKey
    | rsa.RSAPrivateKey
)
_PublicKey = (
    dsa.DSAPublicKey
    | ec.EllipticCurvePublicKey
    | ed25519.Ed25519PublicKey
    | ed448.Ed448PublicKey
    | rsa.RSAPublicKey
)
_Key = _PrivateKey | _PublicKey
PassphraseCallableT = bytes | Callable[..., bytes]
FILETYPE_PEM: int
FILETYPE_ASN1: int
FILETYPE_TEXT: int
TYPE_RSA: int
TYPE_DSA: int
TYPE_DH: int
TYPE_EC: int

class Error(Exception): ...

class _X509NameInvalidator:
    def __init__(self) -> None: ...
    def add(self, name: X509Name) -> None: ...
    def clear(self) -> None: ...

class PKey:
    _only_public: bool
    _initialized: bool
    def __init__(self) -> None: ...
    def to_cryptography_key(self) -> _Key: ...
    @classmethod
    def from_cryptography_key(cls, crypto_key: _Key) -> PKey: ...
    def generate_key(self, type: int, bits: int) -> None: ...
    def check(self) -> bool: ...
    def type(self) -> int: ...
    def bits(self) -> int: ...

class _EllipticCurve:
    def _to_EC_KEY(self) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    @classmethod
    def from_nid(cls, lib: Any, nid: int) -> _EllipticCurve: ...
    name: str
    def __init__(self, lib: Any, nid: int, name: str) -> None: ...

def get_elliptic_curves() -> set[_EllipticCurve]: ...
def get_elliptic_curve(name: str) -> _EllipticCurve: ...

class X509Name:
    def __init__(self, name: X509Name) -> None: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __getattr__(self, name: str) -> str | None: ...
    def __eq__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def hash(self) -> int: ...
    def der(self) -> bytes: ...
    def get_components(self) -> list[tuple[bytes, bytes]]: ...

class X509Req:
    def __init__(self) -> None: ...
    def to_cryptography(self) -> x509.CertificateSigningRequest: ...
    @classmethod
    def from_cryptography(
        cls, crypto_req: x509.CertificateSigningRequest
    ) -> X509Req: ...
    def set_pubkey(self, pkey: PKey) -> None: ...
    def get_pubkey(self) -> PKey: ...
    def set_version(self, version: int) -> None: ...
    def get_version(self) -> int: ...
    def get_subject(self) -> X509Name: ...
    def sign(self, pkey: PKey, digest: str) -> None: ...
    def verify(self, pkey: PKey) -> bool: ...

class X509:
    def __init__(self) -> None: ...
    def to_cryptography(self) -> x509.Certificate: ...
    @classmethod
    def from_cryptography(cls, crypto_cert: x509.Certificate) -> X509: ...
    def set_version(self, version: int) -> None: ...
    def get_version(self) -> int: ...
    def get_pubkey(self) -> PKey: ...
    def set_pubkey(self, pkey: PKey) -> None: ...
    def sign(self, pkey: PKey, digest: str) -> None: ...
    def get_signature_algorithm(self) -> bytes: ...
    def digest(self, digest_name: str) -> bytes: ...
    def subject_name_hash(self) -> int: ...
    def set_serial_number(self, serial: int) -> None: ...
    def get_serial_number(self) -> int: ...
    def gmtime_adj_notAfter(self, amount: int) -> None: ...
    def gmtime_adj_notBefore(self, amount: int) -> None: ...
    def has_expired(self) -> bool: ...
    def get_notBefore(self) -> bytes | None: ...
    def set_notBefore(self, when: bytes) -> None: ...
    def get_notAfter(self) -> bytes | None: ...
    def set_notAfter(self, when: bytes) -> None: ...
    def get_issuer(self) -> X509Name: ...
    def set_issuer(self, issuer: X509Name) -> None: ...
    def get_subject(self) -> X509Name: ...
    def set_subject(self, subject: X509Name) -> None: ...
    def get_extension_count(self) -> int: ...

class X509StoreFlags:
    CRL_CHECK: int
    CRL_CHECK_ALL: int
    IGNORE_CRITICAL: int
    X509_STRICT: int
    ALLOW_PROXY_CERTS: int
    POLICY_CHECK: int
    EXPLICIT_POLICY: int
    INHIBIT_MAP: int
    CHECK_SS_SIGNATURE: int
    PARTIAL_CHAIN: int

class X509Store:
    def __init__(self) -> None: ...
    def add_cert(self, cert: X509) -> None: ...
    def add_crl(self, crl: x509.CertificateRevocationList) -> None: ...
    def set_flags(self, flags: int) -> None: ...
    def set_time(self, vfy_time: datetime.datetime) -> None: ...
    def load_locations(
        self,
        cafile: StrOrBytesPath | None,
        capath: StrOrBytesPath | None = None,
    ) -> None: ...
    def _object_count(self) -> int: ...

class X509StoreContextError(Exception):
    errors: list[Any]
    certificate: X509
    def __init__(
        self, message: str, errors: list[Any], certificate: X509
    ) -> None: ...

class X509StoreContext:
    def __init__(
        self,
        store: X509Store,
        certificate: X509,
        chain: Sequence[X509] | None = None,
    ) -> None: ...
    def set_store(self, store: X509Store) -> None: ...
    def verify_certificate(self) -> None: ...
    def get_verified_chain(self) -> list[X509]: ...

def load_certificate(type: int, buffer: bytes) -> X509: ...
def dump_certificate(type: int, cert: X509) -> bytes: ...
def dump_publickey(type: int, pkey: PKey) -> bytes: ...
def dump_privatekey(
    type: int,
    pkey: PKey,
    cipher: str | None = None,
    passphrase: PassphraseCallableT | None = None,
) -> bytes: ...

class _PassphraseHelper:
    def __init__(
        self,
        type: int,
        passphrase: PassphraseCallableT | None,
        more_args: bool = False,
        truncate: bool = False,
    ) -> None: ...
    @property
    def callback(self) -> Any: ...
    @property
    def callback_args(self) -> Any: ...
    def raise_if_problem(
        self, exceptionType: type[Exception] = ...
    ) -> None: ...

def load_publickey(type: int, buffer: str | bytes) -> PKey: ...
def load_privatekey(
    type: int,
    buffer: str | bytes,
    passphrase: PassphraseCallableT | None = None,
) -> PKey: ...
def dump_certificate_request(type: int, req: X509Req) -> bytes: ...
def load_certificate_request(type: int, buffer: bytes) -> X509Req: ...
