import socket
import typing
from collections.abc import Sequence
from typing import Any, Callable, TypeVar

from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import ec

from OpenSSL._util import StrOrBytesPath as _StrOrBytesPath
from OpenSSL.crypto import FILETYPE_PEM as FILETYPE_PEM
from OpenSSL.crypto import X509 as X509
from OpenSSL.crypto import PKey as PKey
from OpenSSL.crypto import X509Name as X509Name
from OpenSSL.crypto import X509Store as X509Store
from OpenSSL.crypto import _EllipticCurve, _PrivateKey

OPENSSL_VERSION_NUMBER: int
OPENSSL_VERSION: int
OPENSSL_CFLAGS: int
OPENSSL_PLATFORM: int
OPENSSL_DIR: int
OPENSSL_BUILT_ON: int
SSLEAY_VERSION = OPENSSL_VERSION
SSLEAY_CFLAGS = OPENSSL_CFLAGS
SSLEAY_PLATFORM = OPENSSL_PLATFORM
SSLEAY_DIR = OPENSSL_DIR
SSLEAY_BUILT_ON = OPENSSL_BUILT_ON
SENT_SHUTDOWN: int
RECEIVED_SHUTDOWN: int
SSLv23_METHOD: int
TLSv1_METHOD: int
TLSv1_1_METHOD: int
TLSv1_2_METHOD: int
TLS_METHOD: int
TLS_SERVER_METHOD: int
TLS_CLIENT_METHOD: int
DTLS_METHOD: int
DTLS_SERVER_METHOD: int
DTLS_CLIENT_METHOD: int
SSL3_VERSION: int
TLS1_VERSION: int
TLS1_1_VERSION: int
TLS1_2_VERSION: int
TLS1_3_VERSION: int
OP_NO_SSLv2: int
OP_NO_SSLv3: int
OP_NO_TLSv1: int
OP_NO_TLSv1_1: int
OP_NO_TLSv1_2: int
OP_NO_TLSv1_3: int
MODE_RELEASE_BUFFERS: int
OP_SINGLE_DH_USE: int
OP_SINGLE_ECDH_USE: int
OP_EPHEMERAL_RSA: int
OP_MICROSOFT_SESS_ID_BUG: int
OP_NETSCAPE_CHALLENGE_BUG: int
OP_NETSCAPE_REUSE_CIPHER_CHANGE_BUG: int
OP_SSLREF2_REUSE_CERT_TYPE_BUG: int
OP_MICROSOFT_BIG_SSLV3_BUFFER: int
OP_MSIE_SSLV2_RSA_PADDING: int
OP_SSLEAY_080_CLIENT_DH_BUG: int
OP_TLS_D5_BUG: int
OP_TLS_BLOCK_PADDING_BUG: int
OP_DONT_INSERT_EMPTY_FRAGMENTS: int
OP_CIPHER_SERVER_PREFERENCE: int
OP_TLS_ROLLBACK_BUG: int
OP_PKCS1_CHECK_1: int
OP_PKCS1_CHECK_2: int
OP_NETSCAPE_CA_DN_BUG: int
OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG: int
OP_NO_COMPRESSION: int
OP_NO_QUERY_MTU: int
OP_COOKIE_EXCHANGE: int
OP_NO_TICKET: int
OP_NO_RENEGOTIATION: int
OP_IGNORE_UNEXPECTED_EOF: int
OP_LEGACY_SERVER_CONNECT: int
OP_ALL: int
VERIFY_PEER: int
VERIFY_FAIL_IF_NO_PEER_CERT: int
VERIFY_CLIENT_ONCE: int
VERIFY_NONE: int
SESS_CACHE_OFF: int
SESS_CACHE_CLIENT: int
SESS_CACHE_SERVER: int
SESS_CACHE_BOTH: int
SESS_CACHE_NO_AUTO_CLEAR: int
SESS_CACHE_NO_INTERNAL_LOOKUP: int
SESS_CACHE_NO_INTERNAL_STORE: int
SESS_CACHE_NO_INTERNAL: int
SSL_ST_CONNECT: int
SSL_ST_ACCEPT: int
SSL_ST_MASK: int
SSL_CB_LOOP: int
SSL_CB_EXIT: int
SSL_CB_READ: int
SSL_CB_WRITE: int
SSL_CB_ALERT: int
SSL_CB_READ_ALERT: int
SSL_CB_WRITE_ALERT: int
SSL_CB_ACCEPT_LOOP: int
SSL_CB_ACCEPT_EXIT: int
SSL_CB_CONNECT_LOOP: int
SSL_CB_CONNECT_EXIT: int
SSL_CB_HANDSHAKE_START: int
SSL_CB_HANDSHAKE_DONE: int

_T = TypeVar("_T")
_Buffer = bytes | bytearray | memoryview
_ALPNSelectCallback = Callable[
    ["Connection", list[bytes]],
    typing.Union[bytes, "_NoOverlappingProtocols"],
]
_CookieGenerateCallback = Callable[["Connection"], bytes]
_CookieVerifyCallback = Callable[["Connection", bytes], bool]
_OCSPClientCallback = Callable[["Connection", bytes, _T | None], bool]
_OCSPServerCallback = Callable[["Connection", _T | None], bytes]
_PassphraseCallback = Callable[[int, bool, _T | None], bytes]
_VerifyCallback = Callable[["Connection", X509, int, int, int], bool]

class _NoOverlappingProtocols: ...

NO_OVERLAPPING_PROTOCOLS: _NoOverlappingProtocols

class X509VerificationCodes:
    OK: int
    ERR_UNABLE_TO_GET_ISSUER_CERT: int
    ERR_UNABLE_TO_GET_CRL: int
    ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE: int
    ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE: int
    ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY: int
    ERR_CERT_SIGNATURE_FAILURE: int
    ERR_CRL_SIGNATURE_FAILURE: int
    ERR_CERT_NOT_YET_VALID: int
    ERR_CERT_HAS_EXPIRED: int
    ERR_CRL_NOT_YET_VALID: int
    ERR_CRL_HAS_EXPIRED: int
    ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD: int
    ERR_ERROR_IN_CERT_NOT_AFTER_FIELD: int
    ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD: int
    ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD: int
    ERR_OUT_OF_MEM: int
    ERR_DEPTH_ZERO_SELF_SIGNED_CERT: int
    ERR_SELF_SIGNED_CERT_IN_CHAIN: int
    ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY: int
    ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE: int
    ERR_CERT_CHAIN_TOO_LONG: int
    ERR_CERT_REVOKED: int
    ERR_INVALID_CA: int
    ERR_PATH_LENGTH_EXCEEDED: int
    ERR_INVALID_PURPOSE: int
    ERR_CERT_UNTRUSTED: int
    ERR_CERT_REJECTED: int
    ERR_SUBJECT_ISSUER_MISMATCH: int
    ERR_AKID_SKID_MISMATCH: int
    ERR_AKID_ISSUER_SERIAL_MISMATCH: int
    ERR_KEYUSAGE_NO_CERTSIGN: int
    ERR_UNABLE_TO_GET_CRL_ISSUER: int
    ERR_UNHANDLED_CRITICAL_EXTENSION: int
    ERR_KEYUSAGE_NO_CRL_SIGN: int
    ERR_UNHANDLED_CRITICAL_CRL_EXTENSION: int
    ERR_INVALID_NON_CA: int
    ERR_PROXY_PATH_LENGTH_EXCEEDED: int
    ERR_KEYUSAGE_NO_DIGITAL_SIGNATURE: int
    ERR_PROXY_CERTIFICATES_NOT_ALLOWED: int
    ERR_INVALID_EXTENSION: int
    ERR_INVALID_POLICY_EXTENSION: int
    ERR_NO_EXPLICIT_POLICY: int
    ERR_DIFFERENT_CRL_SCOPE: int
    ERR_UNSUPPORTED_EXTENSION_FEATURE: int
    ERR_UNNESTED_RESOURCE: int
    ERR_PERMITTED_VIOLATION: int
    ERR_EXCLUDED_VIOLATION: int
    ERR_SUBTREE_MINMAX: int
    ERR_UNSUPPORTED_CONSTRAINT_TYPE: int
    ERR_UNSUPPORTED_CONSTRAINT_SYNTAX: int
    ERR_UNSUPPORTED_NAME_SYNTAX: int
    ERR_CRL_PATH_VALIDATION_ERROR: int
    ERR_HOSTNAME_MISMATCH: int
    ERR_EMAIL_MISMATCH: int
    ERR_IP_ADDRESS_MISMATCH: int
    ERR_APPLICATION_VERIFICATION: int

class Error(Exception): ...
class WantReadError(Error): ...
class WantWriteError(Error): ...
class WantX509LookupError(Error): ...
class ZeroReturnError(Error): ...
class SysCallError(Error): ...

def OpenSSL_version(type: int) -> bytes: ...

SSLeay_version = OpenSSL_version

class Session: ...

F = TypeVar("F", bound=Callable[..., Any])

class Context:
    def __init__(self, method: int) -> None: ...
    def set_min_proto_version(self, version: int) -> None: ...
    def set_max_proto_version(self, version: int) -> None: ...
    def load_verify_locations(
        self,
        cafile: _StrOrBytesPath | None,
        capath: _StrOrBytesPath | None = None,
    ) -> None: ...
    def set_passwd_cb(
        self, callback: _PassphraseCallback[_T], userdata: _T | None = None
    ) -> None: ...
    def set_default_verify_paths(self) -> None: ...
    def _set_default_verify_paths_openssl(self) -> None: ...
    def _check_env_vars_set(
        self, dir_env_var: str, file_env_var: str
    ) -> bool: ...
    def _fallback_default_verify_paths(
        self, file_path: list[str], dir_path: list[str]
    ) -> None: ...
    def use_certificate_chain_file(
        self, certfile: _StrOrBytesPath
    ) -> None: ...
    def use_certificate_file(
        self, certfile: _StrOrBytesPath, filetype: int = ...
    ) -> None: ...
    def use_certificate(self, cert: X509 | x509.Certificate) -> None: ...
    def add_extra_chain_cert(
        self, certobj: X509 | x509.Certificate
    ) -> None: ...
    def use_privatekey_file(
        self, keyfile: _StrOrBytesPath, filetype: int = ...
    ) -> None: ...
    def use_privatekey(self, pkey: _PrivateKey | PKey) -> None: ...
    def check_privatekey(self) -> None: ...
    def load_client_ca(self, cafile: bytes) -> None: ...
    def set_session_id(self, buf: bytes) -> None: ...
    def set_session_cache_mode(self, mode: int) -> int: ...
    def get_session_cache_mode(self) -> int: ...
    def set_verify(
        self, mode: int, callback: _VerifyCallback | None = None
    ) -> None: ...
    def set_verify_depth(self, depth: int) -> None: ...
    def get_verify_mode(self) -> int: ...
    def get_verify_depth(self) -> int: ...
    def load_tmp_dh(self, dhfile: _StrOrBytesPath) -> None: ...
    def set_tmp_ecdh(
        self, curve: _EllipticCurve | ec.EllipticCurve
    ) -> None: ...
    def set_cipher_list(self, cipher_list: bytes) -> None: ...
    def set_tls13_ciphersuites(self, ciphersuites: bytes) -> None: ...
    def set_client_ca_list(
        self, certificate_authorities: Sequence[X509Name]
    ) -> None: ...
    def add_client_ca(
        self, certificate_authority: X509 | x509.Certificate
    ) -> None: ...
    def set_timeout(self, timeout: int) -> None: ...
    def get_timeout(self) -> int: ...
    def set_info_callback(
        self, callback: Callable[[Connection, int, int], None]
    ) -> None: ...
    def set_keylog_callback(
        self, callback: Callable[[Connection, bytes], None]
    ) -> None: ...
    def get_app_data(self) -> Any: ...
    def set_app_data(self, data: Any) -> None: ...
    def get_cert_store(self) -> X509Store | None: ...
    def set_options(self, options: int) -> int: ...
    def set_mode(self, mode: int) -> int: ...
    def clear_mode(self, mode_to_clear: int) -> int: ...
    def set_tlsext_servername_callback(
        self, callback: Callable[[Connection], None]
    ) -> None: ...
    def set_tlsext_use_srtp(self, profiles: bytes) -> None: ...
    def set_alpn_protos(self, protos: list[bytes]) -> None: ...
    def set_alpn_select_callback(
        self, callback: _ALPNSelectCallback
    ) -> None: ...
    def set_ocsp_server_callback(
        self, callback: _OCSPServerCallback[_T], data: _T | None = None
    ) -> None: ...
    def set_ocsp_client_callback(
        self, callback: _OCSPClientCallback[_T], data: _T | None = None
    ) -> None: ...
    def set_cookie_generate_callback(
        self, callback: _CookieGenerateCallback
    ) -> None: ...
    def set_cookie_verify_callback(
        self, callback: _CookieVerifyCallback
    ) -> None: ...

class Connection:
    def __init__(
        self, context: Context, socket: socket.socket | None = None
    ) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def get_context(self) -> Context: ...
    def set_context(self, context: Context) -> None: ...
    def set_options(self, options: int) -> int: ...
    def get_servername(self) -> bytes | None: ...
    def set_verify(
        self, mode: int, callback: _VerifyCallback | None = None
    ) -> None: ...
    def get_verify_mode(self) -> int: ...
    def use_certificate(self, cert: X509 | x509.Certificate) -> None: ...
    def use_privatekey(self, pkey: _PrivateKey | PKey) -> None: ...
    def set_ciphertext_mtu(self, mtu: int) -> None: ...
    def get_cleartext_mtu(self) -> int: ...
    def set_tlsext_host_name(self, name: bytes) -> None: ...
    def pending(self) -> int: ...
    def send(self, buf: _Buffer, flags: int = 0) -> int: ...
    write = send
    def sendall(self, buf: _Buffer, flags: int = 0) -> int: ...
    def recv(self, bufsiz: int, flags: int | None = None) -> bytes: ...
    read = recv
    def recv_into(
        self, buffer: Any, nbytes: int | None = None, flags: int | None = None
    ) -> int: ...
    def bio_read(self, bufsiz: int) -> bytes: ...
    def bio_write(self, buf: _Buffer) -> int: ...
    def renegotiate(self) -> bool: ...
    def do_handshake(self) -> None: ...
    def renegotiate_pending(self) -> bool: ...
    def total_renegotiations(self) -> int: ...
    def connect(self, addr: Any) -> None: ...
    def connect_ex(self, addr: Any) -> int: ...
    def accept(self) -> tuple[Connection, Any]: ...
    def DTLSv1_listen(self) -> None: ...
    def DTLSv1_get_timeout(self) -> int | None: ...
    def DTLSv1_handle_timeout(self) -> bool: ...
    def bio_shutdown(self) -> None: ...
    def shutdown(self) -> bool: ...
    def get_cipher_list(self) -> list[str]: ...
    def get_client_ca_list(self) -> list[X509Name]: ...
    def makefile(self, *args: Any, **kwargs: Any) -> typing.NoReturn: ...
    def get_app_data(self) -> Any: ...
    def set_app_data(self, data: Any) -> None: ...
    def get_shutdown(self) -> int: ...
    def set_shutdown(self, state: int) -> None: ...
    def get_state_string(self) -> bytes: ...
    def server_random(self) -> bytes | None: ...
    def client_random(self) -> bytes | None: ...
    def master_key(self) -> bytes | None: ...
    def export_keying_material(
        self, label: bytes, olen: int, context: bytes | None = None
    ) -> bytes: ...
    def sock_shutdown(self, *args: Any, **kwargs: Any) -> None: ...
    @typing.overload
    def get_certificate(
        self, *, as_cryptography: typing.Literal[True]
    ) -> x509.Certificate | None: ...
    @typing.overload
    def get_certificate(
        self, *, as_cryptography: typing.Literal[False] = False
    ) -> X509 | None: ...
    @typing.overload
    def get_peer_certificate(
        self, *, as_cryptography: typing.Literal[True]
    ) -> x509.Certificate | None: ...
    @typing.overload
    def get_peer_certificate(
        self, *, as_cryptography: typing.Literal[False] = False
    ) -> X509 | None: ...
    @typing.overload
    def get_peer_cert_chain(
        self, *, as_cryptography: typing.Literal[True]
    ) -> list[x509.Certificate] | None: ...
    @typing.overload
    def get_peer_cert_chain(
        self, *, as_cryptography: typing.Literal[False] = False
    ) -> list[X509] | None: ...
    @typing.overload
    def get_verified_chain(
        self, *, as_cryptography: typing.Literal[True]
    ) -> list[x509.Certificate] | None: ...
    @typing.overload
    def get_verified_chain(
        self, *, as_cryptography: typing.Literal[False] = False
    ) -> list[X509] | None: ...
    def want_read(self) -> bool: ...
    def want_write(self) -> bool: ...
    def set_accept_state(self) -> None: ...
    def set_connect_state(self) -> None: ...
    def get_session(self) -> Session | None: ...
    def set_session(self, session: Session) -> None: ...
    def get_finished(self) -> bytes | None: ...
    def get_peer_finished(self) -> bytes | None: ...
    def get_cipher_name(self) -> str | None: ...
    def get_cipher_bits(self) -> int | None: ...
    def get_cipher_version(self) -> str | None: ...
    def get_protocol_version_name(self) -> str: ...
    def get_protocol_version(self) -> int: ...
    def set_alpn_protos(self, protos: list[bytes]) -> None: ...
    def get_alpn_proto_negotiated(self) -> bytes: ...
    def get_selected_srtp_profile(self) -> bytes: ...
    def get_group_name(self) -> str | None: ...
    def request_ocsp(self) -> None: ...
    def set_info_callback(
        self, callback: Callable[[Connection, int, int], None]
    ) -> None: ...

_HAS_KEYLOG: bool
_HAS_SSL_COOKIE: bool
_HAS_SSL_GET0_GROUP_NAME: bool
_CRYPTOGRAPHY_MANYLINUX_CA_DIR: bytes
_CRYPTOGRAPHY_MANYLINUX_CA_FILE: bytes
_CERTIFICATE_FILE_LOCATIONS: list[str]
_CERTIFICATE_PATH_LOCATIONS: list[str]

def _x509_get_default_cert_file() -> bytes: ...
def _x509_get_default_cert_dir() -> bytes: ...
def _make_requires(flag: int, error: str) -> Callable[[_T], _T]: ...
